#include "ErrorReason.h"
std::map<std::int32_t, std::string> errorCode{
std::make_pair(101,"Out of Range"),
std::make_pair(102,"Parameter Missing"),
std::make_pair(201,"Network Failed"),
std::make_pair(202,"Unavailable"),
std::make_pair(203,"Timeout"),
std::make_pair(301,"Permission Denied"),
std::make_pair(401,"Node not exists"),
std::make_pair(402,"No index passed in"),
std::make_pair(403,"No key passed in"),
std::make_pair(404,"Memory configured error"),
std::make_pair(405,"Value type error"),
std::make_pair(406,"unsupported operation get_length"),
std::make_pair(407,"unsupported operation get_attributes"),
std::make_pair(408,"unsupported operation get_keys"),
std::make_pair(409,"arguments nimiety"),
std::make_pair(410,"key error"),
std::make_pair(411,"Atrribute error"),
std::make_pair(412,"syntax error"),
std::make_pair(413,"keys of arguments error"),
std::make_pair(414,"unsupported terminal identifier"),
std::make_pair(415,"Insufficient dynamic sampling resources"),
std::make_pair(416,"Insufficient event resources"),
std::make_pair(417,"Insufficient method resources"),
std::make_pair(418,"method action type error"),
std::make_pair(419,"filter type error"),
std::make_pair(420,"trigger type error"),
std::make_pair(421,"filter type and arguments not matched")
};